version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=every-io-test
    volumes:
        - ./pgdata/postgres-test:/var/lib/postgresql/data
    ports:
      - '5432:5432'
