version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=every-io
    volumes:
        - ./pgdata/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready --username=admin && psql --username=admin --list"
      timeout: 5s
      retries: 20
  app:
    working_dir: /app
    depends_on:
        db:
          condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: 
      - .env
    environment:
      - NODE_ENV=development
    ports: 
      - '${PORT}:${PORT}'
      - '9222:9222'
    volumes: 
      - ./src:/app/src
    container_name: tasks_api
    command: yarn dev 
